config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users
  
  resources :categories
  
  resources :places do 
    resources :reviews 
  end
  
  namespace :admin do
    get 'index'
    get 'places'
    get 'accept_place'
  end
  
  root 'places#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :places, dependent: :destroy
end

app/models/place.rb
class Place < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :reviews, dependent: :destroy
  
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  validates :agreement, presence: true
  validates :name, presence: true
  validates :description, presence: true
  
  self.per_page = 20
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :place

  validates :food, presence: true
  validates :service, presence: true
  validates :interior, presence: true
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :name, presence: true, length: {maximum: 50}

  has_many :places, dependent: :destroy
  has_many :reviews, dependent: :destroy
  
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :ensure_admin!
  def index
    
  end

  def places
  	@places = Place.all
  end

  def accept_place
    place = Place.find(params[:place])
    place.accepted = true
    respond_to do |format|
      if place.save
        format.html { redirect_to admin_places_url }
      else
        format.html { redirect_to admin_places_url }
      end
    end  
  end

  private

   def ensure_admin!
      unless current_user && current_user.admin?
        redirect_to root_path
      end
    end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?


  def access_denied(exception)
    flash[:danger] = exception.message
    redirect_to root_url
  end

  private
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name, :admin])
    end
    	
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :ensure_admin!


  def index
    @categories = Category.all
  end

  def show
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_back fallback_location: root_path, notice: 'Category was successfully destroyed.' }
    end
  end

  private
    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name)
    end

    def ensure_admin!
      unless current_user && current_user.admin?
        redirect_to root_path
      end
    end

end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: [:show, :edit, :update, :destroy]
  before_action :ensure_login!, only: [:new, :create, :edit, :update]
  def index
    if params[:category]
      @places = Place.where(:category => params[:category]).where(accepted: true).paginate(:page => params[:page])
    else
      @places = Place.where(accepted: true).paginate(:page => params[:page])
    end
    @categories = Category.all
  end

  def show
    @food_average = @place.reviews.average(:food)
    @food_average = @food_average.round(1) if @food_average
    @service_average = @place.reviews.average(:service)
    @service_average = @service_average.round(1) if @service_average
    @interior_average = @place.reviews.average(:interior)
    @interior_average = @interior_average.round(1) if @interior_average
    
    all_average = [@food_average, @service_average, @interior_average]
    if all_average == [nil, nil, nil]
      @overall_average = 0
    else
      @overall_average = (all_average.sum / all_average.size.to_f).round(1) if all_average
    end
  end

  def new
    @place = Place.new
  end

  def edit
  end

  def create
    @place = Place.new(place_params)
    @place.user = current_user
    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: 'Place was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to places_url, notice: 'Place was successfully destroyed.' }
    end
  end

  private
    def set_place
      @place = Place.find(params[:id])
    end

    def place_params
      params.require(:place).permit(:name, :user_id, :category_id, :agreement, :image, :accepted, :description)
    end

    def ensure_login!
      unless user_signed_in?
        redirect_to root_path
      end
    end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  
  def create
    place = Place.find(params[:place_id])
    review = place.reviews.new review_params
    review.user = current_user
    review.save
    redirect_to place_path(place)
  end
  
  def destroy
    place = Place.find(params[:place_id])
    review = place.reviews.find(params[:id]) 
    review.destroy
    respond_to do |format|
      format.html {redirect_to place_path(place), notice: 'Review was successfully destroyed'}
    end
  end

  private
  
    def review_params
      params.require(:review).permit(:food, :service, :interior, :body)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/admin/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table class = "table table-striped">
  <thead>
    <tr>
      <th>Items</th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td><%= link_to 'Categories', categories_path %></td>
     </tr>
     <tr>
       <td><%= link_to 'Places', admin_places_path %></td>   
     </tr>
  </tbody>
</table>

app/views/admin/places.html.erb
<h1>Places</h1>

<table class = "table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Accepted</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
  </thead>

  <tbody>
    <% @places.each do |place| %>
      <tr>
	      <td><%= link_to place.name, place %></td>
	      <% if place.accepted == false %>
	        <td><%= link_to "Accept", admin_accept_place_path(:place =>place) %>
	      <% else %>
	        <td>Accepted</td> 
	      <% end %>
	      <td><%= link_to 'Edit', edit_place_path(place) %></td>
        <td><%= link_to 'Destroy', place, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    	</tr>
    <% end %>
  </tbody>
</table>

<p><%= link_to 'Back', admin_index_url %></p>

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :category_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table class = "table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

<p><%= link_to 'Back', admin_index_url %></p>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Final</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/application/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/layouts/application/_navbar.html.erb
<nav class="navbar navbar-fixed-top navbar-light bg-light">
  <div class="container">
    <div class="navbar-header">  
    <%= link_to 'Main Page', root_path, class: 'navbar-link' %>
    </div>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <p class="navbar-text">
            Hello, <%= link_to current_user.name, edit_user_registration_path(current_user), class: 'navbar-link' %>
          </p>
          <ul class="nav navbar-nav">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <% if current_user.admin? %>
                  <li><%= link_to "Admin Panel", admin_index_url %></li>
                <% end %>
                <li><%=  %></li>
                <li><%= link_to 'Edit profile', edit_user_registration_path(current_user) %></li>
                <li class="divider"></li>
                <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
          </ul>
        <% else %>
          <%= link_to 'Sign up', new_user_registration_path, class: 'btn btn-default navbar-btn' %>
          <%= link_to 'Log in', new_user_session_path, class: 'btn btn-default navbar-btn' %>
        <% end %>
      </ul>
    
  </div>
</nav>

app/views/places/_form.html.erb
<%= form_with(model: place, local: true) do |form| %>
  <% if place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(place.errors.count, "error") %> prohibited this place from being saved:</h2>

      <ul>
      <% place.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, id: :place_name, :required => true %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, id: :place_description, :required => true %>
  </div>

  <div class="form-group">
    <%= form.label :category_id %>
    <%= form.collection_select(:category_id, Category.all, :id, :name, :required => true) %>
  </div>
  
  <div class="form-group">
    <%= form.label :image %>
    <%= form.file_field :image, :required => true %>
  </div>
  
  <div class="form-group">
    <%= form.label "You must agree" %>
    <%= form.check_box :agreement, :required => true %>
  </div>
 


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/places/edit.html.erb
<h1>Editing Place</h1>

<%= render 'form', place: @place %>

<%= link_to 'Show', @place %> |
<%= link_to 'Back', url_for(:back) %>

app/views/places/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Places</h1>

<div class="container-fluid">
  <p>Categories</p>
    <ul>
      <% @categories.each do |category| %>
        <li><%= link_to category.name, places_path(:category=>category.id) %></li>
      <% end %>
    </ul>
  <div class="row">
    <% @places.each do |place| %>
      <div class="col">
        <p><%=image_tag place.image.url(:medium) %></p>
        <p><%= link_to place.name, place_path(place) %></p>
      </div>
    <% end %>
  </div>
  <%= will_paginate @places %>
</div>
<br>
<% if user_signed_in? %>
  <%= link_to 'New Place', new_place_path %>
<% end %>

app/views/places/new.html.erb
<h1>New Place</h1>

<%= render 'form', place: @place %>

<%= link_to 'Back', url_for(:back) %>

app/views/places/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%= @place.name %></strong>
</p>

<p>
  <%= @place.description %>
</p>
<p>
  <%= image_tag @place.image.url(:medium) %>
</p>
<p>Ratings</p>
<p>Overall: <%= @overall_average %></p>
<p>Quality of food: <%= @food_average %></p>
<p>Service quality: <%= @service_average %></p>
<p>Interior: <%= @interior_average %></p>
<hr />
<p>Reviews</p>
<% @place.reviews.each do |review| %>
  <%= render partial: "reviews/review", :locals => {:review => review} %>
  <hr />
<% end %>
<p><strong>Add Review</strong></p>
<%= render partial: "reviews/form" %>

<% if current_user && current_user.id == @place.user.id %>
<%= link_to 'Edit', edit_place_path(@place) %> |
<% end %>
<%= link_to 'Back', url_for(:back) %>

app/views/reviews/_form.html.erb
<%= form_for [@place, Review.new] do |f| %>
  <div class="form-group">
    <p><%= f.text_area :body, :required => true %></p>
    Quality of food:
    <%= f.select :food, [1, 2, 3, 4, 5], :required => true %>
    Service quality:
    <%= f.select :service, [1, 2, 3, 4, 5], :required => true %>
    Interior:
    <%= f.select :interior, [1, 2, 3, 4, 5], :required => true %>
  </div>
  <%= f.submit "Submit Review", class: "btn btn-primary" %>
<% end %>

app/views/reviews/_review.html.erb
<div class = "form-group"> 
  <p><%= review.user.name %> said:</p>
  <p><%= review.body %></p>
  <p>Quality of Food: <%= review.food %></p>
  <p>Service quality: <%= review.service %></p>
  <p>interior: <%= review.interior%></p>
  <% if user_signed_in? && current_user.admin? %>
    <%= link_to "Delete", [@place, review], :method => :delete, data: { confirm: "Are you Sure?" } %> 
  <% end %>
</div>